version: '3.1'
services:
  sftp:
   image: cuipito/easy-sftp:latest
   volumes:
        - /dir/on/host/:/sftp/username
        - /etc/localtime:/etc/localtime:ro
   ports:
     - "222:22"
   secrets:
     - sftpuser-key
   environment:
        SSH_USERNAME: "sftpuser"
        SSH_KEY: "ssh-rsa key"


secrets:
     sftpuser-key:
        external: true
