version: '3.4'
services:
  sftp-build:
   image: cuipito/easy-sftp:test
   volumes:
        - /data/docker/sftp/data:/sftp/twilde
        - /etc/localtime:/etc/localtime:ro
   ports:
     - "2222:22"
   secrets:
     - twilde-key
   environment:
        SSH_USERNAME_1: "twilde"

secrets:
  twilde-key:
    external: true
